// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/service/service.go
//
// Generated by this command:
//
//	mockgen -source=../app/service/service.go -destination=../app/service/mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Andriy-Sydorenko/repo-release-notifier/internal/app/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepo is a mock of SubscriptionRepo interface.
type MockSubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepoMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepoMockRecorder is the mock recorder for MockSubscriptionRepo.
type MockSubscriptionRepoMockRecorder struct {
	mock *MockSubscriptionRepo
}

// NewMockSubscriptionRepo creates a new mock instance.
func NewMockSubscriptionRepo(ctrl *gomock.Controller) *MockSubscriptionRepo {
	mock := &MockSubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepo) EXPECT() *MockSubscriptionRepoMockRecorder {
	return m.recorder
}

// ConfirmSubscription mocks base method.
func (m *MockSubscriptionRepo) ConfirmSubscription(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmSubscription indicates an expected call of ConfirmSubscription.
func (mr *MockSubscriptionRepoMockRecorder) ConfirmSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSubscription", reflect.TypeOf((*MockSubscriptionRepo)(nil).ConfirmSubscription), ctx, id)
}

// DeleteSubscription mocks base method.
func (m *MockSubscriptionRepo) DeleteSubscription(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockSubscriptionRepoMockRecorder) DeleteSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockSubscriptionRepo)(nil).DeleteSubscription), ctx, id)
}

// FindSubscriptionByUnsubscribeToken mocks base method.
func (m *MockSubscriptionRepo) FindSubscriptionByUnsubscribeToken(ctx context.Context, token string) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionByUnsubscribeToken", ctx, token)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptionByUnsubscribeToken indicates an expected call of FindSubscriptionByUnsubscribeToken.
func (mr *MockSubscriptionRepoMockRecorder) FindSubscriptionByUnsubscribeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionByUnsubscribeToken", reflect.TypeOf((*MockSubscriptionRepo)(nil).FindSubscriptionByUnsubscribeToken), ctx, token)
}

// FindSubscriptionsByEmail mocks base method.
func (m *MockSubscriptionRepo) FindSubscriptionsByEmail(ctx context.Context, email string) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionsByEmail", ctx, email)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptionsByEmail indicates an expected call of FindSubscriptionsByEmail.
func (mr *MockSubscriptionRepoMockRecorder) FindSubscriptionsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionsByEmail", reflect.TypeOf((*MockSubscriptionRepo)(nil).FindSubscriptionsByEmail), ctx, email)
}

// MockTokenRepo is a mock of TokenRepo interface.
type MockTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepoMockRecorder
	isgomock struct{}
}

// MockTokenRepoMockRecorder is the mock recorder for MockTokenRepo.
type MockTokenRepoMockRecorder struct {
	mock *MockTokenRepo
}

// NewMockTokenRepo creates a new mock instance.
func NewMockTokenRepo(ctrl *gomock.Controller) *MockTokenRepo {
	mock := &MockTokenRepo{ctrl: ctrl}
	mock.recorder = &MockTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepo) EXPECT() *MockTokenRepoMockRecorder {
	return m.recorder
}

// FindTokenByValue mocks base method.
func (m *MockTokenRepo) FindTokenByValue(ctx context.Context, tokenValue string) (*domain.ConfirmationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTokenByValue", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.ConfirmationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTokenByValue indicates an expected call of FindTokenByValue.
func (mr *MockTokenRepoMockRecorder) FindTokenByValue(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTokenByValue", reflect.TypeOf((*MockTokenRepo)(nil).FindTokenByValue), ctx, tokenValue)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// SubscriptionRemoved mocks base method.
func (m *MockEventPublisher) SubscriptionRemoved(ctx context.Context, subscriptionID, repo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriptionRemoved", ctx, subscriptionID, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscriptionRemoved indicates an expected call of SubscriptionRemoved.
func (mr *MockEventPublisherMockRecorder) SubscriptionRemoved(ctx, subscriptionID, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriptionRemoved", reflect.TypeOf((*MockEventPublisher)(nil).SubscriptionRemoved), ctx, subscriptionID, repo)
}
