// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/service/service.go
//
// Generated by this command:
//
//	mockgen -source=../app/service/service.go -destination=../app/service/mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Andriy-Sydorenko/repo-release-notifier/internal/app/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepo is a mock of SubscriptionRepo interface.
type MockSubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepoMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepoMockRecorder is the mock recorder for MockSubscriptionRepo.
type MockSubscriptionRepoMockRecorder struct {
	mock *MockSubscriptionRepo
}

// NewMockSubscriptionRepo creates a new mock instance.
func NewMockSubscriptionRepo(ctrl *gomock.Controller) *MockSubscriptionRepo {
	mock := &MockSubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepo) EXPECT() *MockSubscriptionRepoMockRecorder {
	return m.recorder
}

// ConfirmSubscription mocks base method.
func (m *MockSubscriptionRepo) ConfirmSubscription(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmSubscription indicates an expected call of ConfirmSubscription.
func (mr *MockSubscriptionRepoMockRecorder) ConfirmSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSubscription", reflect.TypeOf((*MockSubscriptionRepo)(nil).ConfirmSubscription), ctx, id)
}

// CreateSubscriptionWithToken mocks base method.
func (m *MockSubscriptionRepo) CreateSubscriptionWithToken(ctx context.Context, sub *domain.Subscription, token *domain.ConfirmationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionWithToken", ctx, sub, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscriptionWithToken indicates an expected call of CreateSubscriptionWithToken.
func (mr *MockSubscriptionRepoMockRecorder) CreateSubscriptionWithToken(ctx, sub, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionWithToken", reflect.TypeOf((*MockSubscriptionRepo)(nil).CreateSubscriptionWithToken), ctx, sub, token)
}

// DeleteSubscription mocks base method.
func (m *MockSubscriptionRepo) DeleteSubscription(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockSubscriptionRepoMockRecorder) DeleteSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockSubscriptionRepo)(nil).DeleteSubscription), ctx, id)
}

// FindSubscriptionByEmailAndRepo mocks base method.
func (m *MockSubscriptionRepo) FindSubscriptionByEmailAndRepo(ctx context.Context, email, repo string) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionByEmailAndRepo", ctx, email, repo)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptionByEmailAndRepo indicates an expected call of FindSubscriptionByEmailAndRepo.
func (mr *MockSubscriptionRepoMockRecorder) FindSubscriptionByEmailAndRepo(ctx, email, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionByEmailAndRepo", reflect.TypeOf((*MockSubscriptionRepo)(nil).FindSubscriptionByEmailAndRepo), ctx, email, repo)
}

// FindSubscriptionByUnsubscribeToken mocks base method.
func (m *MockSubscriptionRepo) FindSubscriptionByUnsubscribeToken(ctx context.Context, token string) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionByUnsubscribeToken", ctx, token)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptionByUnsubscribeToken indicates an expected call of FindSubscriptionByUnsubscribeToken.
func (mr *MockSubscriptionRepoMockRecorder) FindSubscriptionByUnsubscribeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionByUnsubscribeToken", reflect.TypeOf((*MockSubscriptionRepo)(nil).FindSubscriptionByUnsubscribeToken), ctx, token)
}

// FindSubscriptionsByEmail mocks base method.
func (m *MockSubscriptionRepo) FindSubscriptionsByEmail(ctx context.Context, email string) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionsByEmail", ctx, email)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSubscriptionsByEmail indicates an expected call of FindSubscriptionsByEmail.
func (mr *MockSubscriptionRepoMockRecorder) FindSubscriptionsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionsByEmail", reflect.TypeOf((*MockSubscriptionRepo)(nil).FindSubscriptionsByEmail), ctx, email)
}

// MockTokenRepo is a mock of TokenRepo interface.
type MockTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepoMockRecorder
	isgomock struct{}
}

// MockTokenRepoMockRecorder is the mock recorder for MockTokenRepo.
type MockTokenRepoMockRecorder struct {
	mock *MockTokenRepo
}

// NewMockTokenRepo creates a new mock instance.
func NewMockTokenRepo(ctrl *gomock.Controller) *MockTokenRepo {
	mock := &MockTokenRepo{ctrl: ctrl}
	mock.recorder = &MockTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepo) EXPECT() *MockTokenRepoMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockTokenRepo) DeleteToken(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockTokenRepoMockRecorder) DeleteToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockTokenRepo)(nil).DeleteToken), ctx, id)
}

// FindTokenByValue mocks base method.
func (m *MockTokenRepo) FindTokenByValue(ctx context.Context, tokenValue string) (*domain.ConfirmationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTokenByValue", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.ConfirmationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTokenByValue indicates an expected call of FindTokenByValue.
func (mr *MockTokenRepoMockRecorder) FindTokenByValue(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTokenByValue", reflect.TypeOf((*MockTokenRepo)(nil).FindTokenByValue), ctx, tokenValue)
}

// MockRepoValidator is a mock of RepoValidator interface.
type MockRepoValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRepoValidatorMockRecorder
	isgomock struct{}
}

// MockRepoValidatorMockRecorder is the mock recorder for MockRepoValidator.
type MockRepoValidatorMockRecorder struct {
	mock *MockRepoValidator
}

// NewMockRepoValidator creates a new mock instance.
func NewMockRepoValidator(ctrl *gomock.Controller) *MockRepoValidator {
	mock := &MockRepoValidator{ctrl: ctrl}
	mock.recorder = &MockRepoValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoValidator) EXPECT() *MockRepoValidatorMockRecorder {
	return m.recorder
}

// ValidateRepo mocks base method.
func (m *MockRepoValidator) ValidateRepo(ctx context.Context, owner, repo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRepo", ctx, owner, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRepo indicates an expected call of ValidateRepo.
func (mr *MockRepoValidatorMockRecorder) ValidateRepo(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRepo", reflect.TypeOf((*MockRepoValidator)(nil).ValidateRepo), ctx, owner, repo)
}

// MockConfirmationSender is a mock of ConfirmationSender interface.
type MockConfirmationSender struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationSenderMockRecorder
	isgomock struct{}
}

// MockConfirmationSenderMockRecorder is the mock recorder for MockConfirmationSender.
type MockConfirmationSenderMockRecorder struct {
	mock *MockConfirmationSender
}

// NewMockConfirmationSender creates a new mock instance.
func NewMockConfirmationSender(ctrl *gomock.Controller) *MockConfirmationSender {
	mock := &MockConfirmationSender{ctrl: ctrl}
	mock.recorder = &MockConfirmationSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationSender) EXPECT() *MockConfirmationSenderMockRecorder {
	return m.recorder
}

// SendConfirmation mocks base method.
func (m *MockConfirmationSender) SendConfirmation(ctx context.Context, email, repo, token, unsubscribeToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmation", ctx, email, repo, token, unsubscribeToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmation indicates an expected call of SendConfirmation.
func (mr *MockConfirmationSenderMockRecorder) SendConfirmation(ctx, email, repo, token, unsubscribeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmation", reflect.TypeOf((*MockConfirmationSender)(nil).SendConfirmation), ctx, email, repo, token, unsubscribeToken)
}
