exclude: '^\.idea/|^vendor/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^\.idea/'
      - id: end-of-file-fixer
        exclude: '^\.idea/'
      - id: check-yaml
        exclude: '^\.idea/'
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=500']

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:

      - id: go-fmt
        exclude: '(^|/)mocks/'
      - id: go-imports
        args: ['-local', 'github.com/Andriy-Sydorenko/repo-release-notifier']
        exclude: '(^|/)mocks/'
      - id: go-unit-tests

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.11.4
    hooks:
      - id: golangci-lint-full
