// Code generated by MockGen. DO NOT EDIT.
// Source: ../orchestrator/service/transport.go
//
// Generated by this command:
//
//	mockgen -source=../orchestrator/service/transport.go -destination=../orchestrator/service/mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Andriy-Sydorenko/repo-release-notifier/internal/orchestrator/domain"
	saga "github.com/Andriy-Sydorenko/repo-release-notifier/internal/shared/saga"
	gomock "go.uber.org/mock/gomock"
)

// MockParticipants is a mock of Participants interface.
type MockParticipants struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantsMockRecorder
	isgomock struct{}
}

// MockParticipantsMockRecorder is the mock recorder for MockParticipants.
type MockParticipantsMockRecorder struct {
	mock *MockParticipants
}

// NewMockParticipants creates a new mock instance.
func NewMockParticipants(ctrl *gomock.Controller) *MockParticipants {
	mock := &MockParticipants{ctrl: ctrl}
	mock.recorder = &MockParticipantsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipants) EXPECT() *MockParticipantsMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockParticipants) CreateSubscription(ctx context.Context, cmd *saga.CreateSubscriptionCommand) (saga.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, cmd)
	ret0, _ := ret[0].(saga.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockParticipantsMockRecorder) CreateSubscription(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockParticipants)(nil).CreateSubscription), ctx, cmd)
}

// RegisterRepo mocks base method.
func (m *MockParticipants) RegisterRepo(ctx context.Context, sagaID, subscriptionID, repo string) (saga.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRepo", ctx, sagaID, subscriptionID, repo)
	ret0, _ := ret[0].(saga.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterRepo indicates an expected call of RegisterRepo.
func (mr *MockParticipantsMockRecorder) RegisterRepo(ctx, sagaID, subscriptionID, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRepo", reflect.TypeOf((*MockParticipants)(nil).RegisterRepo), ctx, sagaID, subscriptionID, repo)
}

// ReleaseRepo mocks base method.
func (m *MockParticipants) ReleaseRepo(ctx context.Context, subscriptionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseRepo", ctx, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseRepo indicates an expected call of ReleaseRepo.
func (mr *MockParticipantsMockRecorder) ReleaseRepo(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRepo", reflect.TypeOf((*MockParticipants)(nil).ReleaseRepo), ctx, subscriptionID)
}

// MockConfirmationPublisher is a mock of ConfirmationPublisher interface.
type MockConfirmationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationPublisherMockRecorder
	isgomock struct{}
}

// MockConfirmationPublisherMockRecorder is the mock recorder for MockConfirmationPublisher.
type MockConfirmationPublisherMockRecorder struct {
	mock *MockConfirmationPublisher
}

// NewMockConfirmationPublisher creates a new mock instance.
func NewMockConfirmationPublisher(ctrl *gomock.Controller) *MockConfirmationPublisher {
	mock := &MockConfirmationPublisher{ctrl: ctrl}
	mock.recorder = &MockConfirmationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationPublisher) EXPECT() *MockConfirmationPublisherMockRecorder {
	return m.recorder
}

// RequestConfirmation mocks base method.
func (m *MockConfirmationPublisher) RequestConfirmation(ctx context.Context, email, repo, confirmToken, unsubToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestConfirmation", ctx, email, repo, confirmToken, unsubToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestConfirmation indicates an expected call of RequestConfirmation.
func (mr *MockConfirmationPublisherMockRecorder) RequestConfirmation(ctx, email, repo, confirmToken, unsubToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestConfirmation", reflect.TypeOf((*MockConfirmationPublisher)(nil).RequestConfirmation), ctx, email, repo, confirmToken, unsubToken)
}

// MockSagaStore is a mock of SagaStore interface.
type MockSagaStore struct {
	ctrl     *gomock.Controller
	recorder *MockSagaStoreMockRecorder
	isgomock struct{}
}

// MockSagaStoreMockRecorder is the mock recorder for MockSagaStore.
type MockSagaStoreMockRecorder struct {
	mock *MockSagaStore
}

// NewMockSagaStore creates a new mock instance.
func NewMockSagaStore(ctrl *gomock.Controller) *MockSagaStore {
	mock := &MockSagaStore{ctrl: ctrl}
	mock.recorder = &MockSagaStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSagaStore) EXPECT() *MockSagaStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSagaStore) Create(ctx context.Context, rec *domain.SagaRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSagaStoreMockRecorder) Create(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSagaStore)(nil).Create), ctx, rec)
}

// FindUnfinished mocks base method.
func (m *MockSagaStore) FindUnfinished(ctx context.Context) ([]domain.SagaRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUnfinished", ctx)
	ret0, _ := ret[0].([]domain.SagaRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUnfinished indicates an expected call of FindUnfinished.
func (mr *MockSagaStoreMockRecorder) FindUnfinished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUnfinished", reflect.TypeOf((*MockSagaStore)(nil).FindUnfinished), ctx)
}

// SetState mocks base method.
func (m *MockSagaStore) SetState(ctx context.Context, sagaID string, state domain.State, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, sagaID, state, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockSagaStoreMockRecorder) SetState(ctx, sagaID, state, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockSagaStore)(nil).SetState), ctx, sagaID, state, lastErr)
}

// MockIDGen is a mock of IDGen interface.
type MockIDGen struct {
	ctrl     *gomock.Controller
	recorder *MockIDGenMockRecorder
	isgomock struct{}
}

// MockIDGenMockRecorder is the mock recorder for MockIDGen.
type MockIDGenMockRecorder struct {
	mock *MockIDGen
}

// NewMockIDGen creates a new mock instance.
func NewMockIDGen(ctrl *gomock.Controller) *MockIDGen {
	mock := &MockIDGen{ctrl: ctrl}
	mock.recorder = &MockIDGenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGen) EXPECT() *MockIDGenMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDGen) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDGenMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDGen)(nil).NewID))
}

// NewToken mocks base method.
func (m *MockIDGen) NewToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewToken indicates an expected call of NewToken.
func (mr *MockIDGenMockRecorder) NewToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewToken", reflect.TypeOf((*MockIDGen)(nil).NewToken))
}
