// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notifier/v1/notifier.proto

package notifierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All fields required; empties are rejected with InvalidArgument.
type SendEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientEmail string                 `protobuf:"bytes,1,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	Subject        string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody       string                 `protobuf:"bytes,3,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_notifier_v1_notifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

// Empty: success is conveyed by the OK status.
type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_notifier_v1_notifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_v1_notifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_notifier_v1_notifier_proto_rawDescGZIP(), []int{1}
}

var File_notifier_v1_notifier_proto protoreflect.FileDescriptor

const file_notifier_v1_notifier_proto_rawDesc = "" +
	"\n" +
	"\x1anotifier/v1/notifier.proto\x12\vnotifier.v1\"r\n" +
	"\x10SendEmailRequest\x12'\n" +
	"\x0frecipient_email\x18\x01 \x01(\tR\x0erecipientEmail\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\thtml_body\x18\x03 \x01(\tR\bhtmlBody\"\x13\n" +
	"\x11SendEmailResponse2]\n" +
	"\x0fNotifierService\x12J\n" +
	"\tSendEmail\x12\x1d.notifier.v1.SendEmailRequest\x1a\x1e.notifier.v1.SendEmailResponseBYZWgithub.com/Andriy-Sydorenko/repo-release-notifier/internal/shared/notifierpb;notifierpbb\x06proto3"

var (
	file_notifier_v1_notifier_proto_rawDescOnce sync.Once
	file_notifier_v1_notifier_proto_rawDescData []byte
)

func file_notifier_v1_notifier_proto_rawDescGZIP() []byte {
	file_notifier_v1_notifier_proto_rawDescOnce.Do(func() {
		file_notifier_v1_notifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifier_v1_notifier_proto_rawDesc), len(file_notifier_v1_notifier_proto_rawDesc)))
	})
	return file_notifier_v1_notifier_proto_rawDescData
}

var file_notifier_v1_notifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notifier_v1_notifier_proto_goTypes = []any{
	(*SendEmailRequest)(nil),  // 0: notifier.v1.SendEmailRequest
	(*SendEmailResponse)(nil), // 1: notifier.v1.SendEmailResponse
}
var file_notifier_v1_notifier_proto_depIdxs = []int32{
	0, // 0: notifier.v1.NotifierService.SendEmail:input_type -> notifier.v1.SendEmailRequest
	1, // 1: notifier.v1.NotifierService.SendEmail:output_type -> notifier.v1.SendEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notifier_v1_notifier_proto_init() }
func file_notifier_v1_notifier_proto_init() {
	if File_notifier_v1_notifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifier_v1_notifier_proto_rawDesc), len(file_notifier_v1_notifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifier_v1_notifier_proto_goTypes,
		DependencyIndexes: file_notifier_v1_notifier_proto_depIdxs,
		MessageInfos:      file_notifier_v1_notifier_proto_msgTypes,
	}.Build()
	File_notifier_v1_notifier_proto = out.File
	file_notifier_v1_notifier_proto_goTypes = nil
	file_notifier_v1_notifier_proto_depIdxs = nil
}
