// Code generated by MockGen. DO NOT EDIT.
// Source: ../catalog/scanner/scanner.go
//
// Generated by this command:
//
//	mockgen -source=../catalog/scanner/scanner.go -destination=../catalog/scanner/mocks/scanner_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalog "github.com/Andriy-Sydorenko/repo-release-notifier/internal/catalog"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ActiveRepos mocks base method.
func (m *MockRepository) ActiveRepos(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveRepos", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveRepos indicates an expected call of ActiveRepos.
func (mr *MockRepositoryMockRecorder) ActiveRepos(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveRepos", reflect.TypeOf((*MockRepository)(nil).ActiveRepos), ctx)
}

// GetWatchedRepo mocks base method.
func (m *MockRepository) GetWatchedRepo(ctx context.Context, repo string) (*catalog.WatchedRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchedRepo", ctx, repo)
	ret0, _ := ret[0].(*catalog.WatchedRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchedRepo indicates an expected call of GetWatchedRepo.
func (mr *MockRepositoryMockRecorder) GetWatchedRepo(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchedRepo", reflect.TypeOf((*MockRepository)(nil).GetWatchedRepo), ctx, repo)
}

// SaveWatchedRepoTag mocks base method.
func (m *MockRepository) SaveWatchedRepoTag(ctx context.Context, repo, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWatchedRepoTag", ctx, repo, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWatchedRepoTag indicates an expected call of SaveWatchedRepoTag.
func (mr *MockRepositoryMockRecorder) SaveWatchedRepoTag(ctx, repo, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWatchedRepoTag", reflect.TypeOf((*MockRepository)(nil).SaveWatchedRepoTag), ctx, repo, tag)
}

// MockReleaseFetcher is a mock of ReleaseFetcher interface.
type MockReleaseFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseFetcherMockRecorder
	isgomock struct{}
}

// MockReleaseFetcherMockRecorder is the mock recorder for MockReleaseFetcher.
type MockReleaseFetcherMockRecorder struct {
	mock *MockReleaseFetcher
}

// NewMockReleaseFetcher creates a new mock instance.
func NewMockReleaseFetcher(ctrl *gomock.Controller) *MockReleaseFetcher {
	mock := &MockReleaseFetcher{ctrl: ctrl}
	mock.recorder = &MockReleaseFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseFetcher) EXPECT() *MockReleaseFetcherMockRecorder {
	return m.recorder
}

// GetLatestRelease mocks base method.
func (m *MockReleaseFetcher) GetLatestRelease(ctx context.Context, owner, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, owner, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRelease indicates an expected call of GetLatestRelease.
func (mr *MockReleaseFetcherMockRecorder) GetLatestRelease(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*MockReleaseFetcher)(nil).GetLatestRelease), ctx, owner, repo)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// ReleaseDetected mocks base method.
func (m *MockEventPublisher) ReleaseDetected(ctx context.Context, repo, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseDetected", ctx, repo, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseDetected indicates an expected call of ReleaseDetected.
func (mr *MockEventPublisherMockRecorder) ReleaseDetected(ctx, repo, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseDetected", reflect.TypeOf((*MockEventPublisher)(nil).ReleaseDetected), ctx, repo, tag)
}
