// Code generated by MockGen. DO NOT EDIT.
// Source: ../catalog/handler.go
//
// Generated by this command:
//
//	mockgen -source=../catalog/handler.go -destination=../catalog/mocks/catalog_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepoValidator is a mock of RepoValidator interface.
type MockRepoValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRepoValidatorMockRecorder
	isgomock struct{}
}

// MockRepoValidatorMockRecorder is the mock recorder for MockRepoValidator.
type MockRepoValidatorMockRecorder struct {
	mock *MockRepoValidator
}

// NewMockRepoValidator creates a new mock instance.
func NewMockRepoValidator(ctrl *gomock.Controller) *MockRepoValidator {
	mock := &MockRepoValidator{ctrl: ctrl}
	mock.recorder = &MockRepoValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoValidator) EXPECT() *MockRepoValidatorMockRecorder {
	return m.recorder
}

// ValidateRepo mocks base method.
func (m *MockRepoValidator) ValidateRepo(ctx context.Context, owner, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRepo", ctx, owner, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRepo indicates an expected call of ValidateRepo.
func (mr *MockRepoValidatorMockRecorder) ValidateRepo(ctx, owner, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRepo", reflect.TypeOf((*MockRepoValidator)(nil).ValidateRepo), ctx, owner, name)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockStore) Register(ctx context.Context, subscriptionID, repo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, subscriptionID, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockStoreMockRecorder) Register(ctx, subscriptionID, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockStore)(nil).Register), ctx, subscriptionID, repo)
}

// Release mocks base method.
func (m *MockStore) Release(ctx context.Context, subscriptionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockStoreMockRecorder) Release(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockStore)(nil).Release), ctx, subscriptionID)
}
