// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/scanner/scanner.go
//
// Generated by this command:
//
//	mockgen -source=../app/scanner/scanner.go -destination=../app/scanner/mocks/scanner_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Andriy-Sydorenko/repo-release-notifier/internal/app/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindConfirmedSubscriptionsByRepo mocks base method.
func (m *MockRepository) FindConfirmedSubscriptionsByRepo(ctx context.Context, repo string) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindConfirmedSubscriptionsByRepo", ctx, repo)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindConfirmedSubscriptionsByRepo indicates an expected call of FindConfirmedSubscriptionsByRepo.
func (mr *MockRepositoryMockRecorder) FindConfirmedSubscriptionsByRepo(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindConfirmedSubscriptionsByRepo", reflect.TypeOf((*MockRepository)(nil).FindConfirmedSubscriptionsByRepo), ctx, repo)
}

// FindDistinctConfirmedRepos mocks base method.
func (m *MockRepository) FindDistinctConfirmedRepos(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDistinctConfirmedRepos", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDistinctConfirmedRepos indicates an expected call of FindDistinctConfirmedRepos.
func (mr *MockRepositoryMockRecorder) FindDistinctConfirmedRepos(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDistinctConfirmedRepos", reflect.TypeOf((*MockRepository)(nil).FindDistinctConfirmedRepos), ctx)
}

// GetWatchedRepo mocks base method.
func (m *MockRepository) GetWatchedRepo(ctx context.Context, repo string) (*domain.WatchedRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchedRepo", ctx, repo)
	ret0, _ := ret[0].(*domain.WatchedRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchedRepo indicates an expected call of GetWatchedRepo.
func (mr *MockRepositoryMockRecorder) GetWatchedRepo(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchedRepo", reflect.TypeOf((*MockRepository)(nil).GetWatchedRepo), ctx, repo)
}

// SaveWatchedRepoTag mocks base method.
func (m *MockRepository) SaveWatchedRepoTag(ctx context.Context, repo, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWatchedRepoTag", ctx, repo, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWatchedRepoTag indicates an expected call of SaveWatchedRepoTag.
func (mr *MockRepositoryMockRecorder) SaveWatchedRepoTag(ctx, repo, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWatchedRepoTag", reflect.TypeOf((*MockRepository)(nil).SaveWatchedRepoTag), ctx, repo, tag)
}

// MockReleaseFetcher is a mock of ReleaseFetcher interface.
type MockReleaseFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseFetcherMockRecorder
	isgomock struct{}
}

// MockReleaseFetcherMockRecorder is the mock recorder for MockReleaseFetcher.
type MockReleaseFetcherMockRecorder struct {
	mock *MockReleaseFetcher
}

// NewMockReleaseFetcher creates a new mock instance.
func NewMockReleaseFetcher(ctrl *gomock.Controller) *MockReleaseFetcher {
	mock := &MockReleaseFetcher{ctrl: ctrl}
	mock.recorder = &MockReleaseFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseFetcher) EXPECT() *MockReleaseFetcherMockRecorder {
	return m.recorder
}

// GetLatestRelease mocks base method.
func (m *MockReleaseFetcher) GetLatestRelease(ctx context.Context, owner, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, owner, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRelease indicates an expected call of GetLatestRelease.
func (mr *MockReleaseFetcherMockRecorder) GetLatestRelease(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*MockReleaseFetcher)(nil).GetLatestRelease), ctx, owner, repo)
}

// MockReleaseNotifier is a mock of ReleaseNotifier interface.
type MockReleaseNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseNotifierMockRecorder
	isgomock struct{}
}

// MockReleaseNotifierMockRecorder is the mock recorder for MockReleaseNotifier.
type MockReleaseNotifierMockRecorder struct {
	mock *MockReleaseNotifier
}

// NewMockReleaseNotifier creates a new mock instance.
func NewMockReleaseNotifier(ctrl *gomock.Controller) *MockReleaseNotifier {
	mock := &MockReleaseNotifier{ctrl: ctrl}
	mock.recorder = &MockReleaseNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseNotifier) EXPECT() *MockReleaseNotifierMockRecorder {
	return m.recorder
}

// SendReleaseNotification mocks base method.
func (m *MockReleaseNotifier) SendReleaseNotification(ctx context.Context, email, repo, tag, unsubscribeToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReleaseNotification", ctx, email, repo, tag, unsubscribeToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReleaseNotification indicates an expected call of SendReleaseNotification.
func (mr *MockReleaseNotifierMockRecorder) SendReleaseNotification(ctx, email, repo, tag, unsubscribeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReleaseNotification", reflect.TypeOf((*MockReleaseNotifier)(nil).SendReleaseNotification), ctx, email, repo, tag, unsubscribeToken)
}
