// Code generated by MockGen. DO NOT EDIT.
// Source: ../scanner/scanner.go
//
// Generated by this command:
//
//	mockgen -source=../scanner/scanner.go -destination=../scanner/mocks/scanner_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	subscription "github.com/Andriy-Sydorenko/repo-release-notifier/internal/subscription"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriberLister is a mock of SubscriberLister interface.
type MockSubscriberLister struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberListerMockRecorder
	isgomock struct{}
}

// MockSubscriberListerMockRecorder is the mock recorder for MockSubscriberLister.
type MockSubscriberListerMockRecorder struct {
	mock *MockSubscriberLister
}

// NewMockSubscriberLister creates a new mock instance.
func NewMockSubscriberLister(ctrl *gomock.Controller) *MockSubscriberLister {
	mock := &MockSubscriberLister{ctrl: ctrl}
	mock.recorder = &MockSubscriberListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriberLister) EXPECT() *MockSubscriberListerMockRecorder {
	return m.recorder
}

// ListConfirmedRepos mocks base method.
func (m *MockSubscriberLister) ListConfirmedRepos(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfirmedRepos", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfirmedRepos indicates an expected call of ListConfirmedRepos.
func (mr *MockSubscriberListerMockRecorder) ListConfirmedRepos(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfirmedRepos", reflect.TypeOf((*MockSubscriberLister)(nil).ListConfirmedRepos), ctx)
}

// ListConfirmedSubscribers mocks base method.
func (m *MockSubscriberLister) ListConfirmedSubscribers(ctx context.Context, repo string) ([]subscription.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfirmedSubscribers", ctx, repo)
	ret0, _ := ret[0].([]subscription.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfirmedSubscribers indicates an expected call of ListConfirmedSubscribers.
func (mr *MockSubscriberListerMockRecorder) ListConfirmedSubscribers(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfirmedSubscribers", reflect.TypeOf((*MockSubscriberLister)(nil).ListConfirmedSubscribers), ctx, repo)
}

// MockWatchedRepoStore is a mock of WatchedRepoStore interface.
type MockWatchedRepoStore struct {
	ctrl     *gomock.Controller
	recorder *MockWatchedRepoStoreMockRecorder
	isgomock struct{}
}

// MockWatchedRepoStoreMockRecorder is the mock recorder for MockWatchedRepoStore.
type MockWatchedRepoStoreMockRecorder struct {
	mock *MockWatchedRepoStore
}

// NewMockWatchedRepoStore creates a new mock instance.
func NewMockWatchedRepoStore(ctrl *gomock.Controller) *MockWatchedRepoStore {
	mock := &MockWatchedRepoStore{ctrl: ctrl}
	mock.recorder = &MockWatchedRepoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchedRepoStore) EXPECT() *MockWatchedRepoStoreMockRecorder {
	return m.recorder
}

// GetLastSeenTag mocks base method.
func (m *MockWatchedRepoStore) GetLastSeenTag(ctx context.Context, repo string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSeenTag", ctx, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastSeenTag indicates an expected call of GetLastSeenTag.
func (mr *MockWatchedRepoStoreMockRecorder) GetLastSeenTag(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSeenTag", reflect.TypeOf((*MockWatchedRepoStore)(nil).GetLastSeenTag), ctx, repo)
}

// UpsertLastSeenTag mocks base method.
func (m *MockWatchedRepoStore) UpsertLastSeenTag(ctx context.Context, repo, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLastSeenTag", ctx, repo, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertLastSeenTag indicates an expected call of UpsertLastSeenTag.
func (mr *MockWatchedRepoStoreMockRecorder) UpsertLastSeenTag(ctx, repo, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLastSeenTag", reflect.TypeOf((*MockWatchedRepoStore)(nil).UpsertLastSeenTag), ctx, repo, tag)
}

// MockRepoValidator is a mock of RepoValidator interface.
type MockRepoValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRepoValidatorMockRecorder
	isgomock struct{}
}

// MockRepoValidatorMockRecorder is the mock recorder for MockRepoValidator.
type MockRepoValidatorMockRecorder struct {
	mock *MockRepoValidator
}

// NewMockRepoValidator creates a new mock instance.
func NewMockRepoValidator(ctrl *gomock.Controller) *MockRepoValidator {
	mock := &MockRepoValidator{ctrl: ctrl}
	mock.recorder = &MockRepoValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoValidator) EXPECT() *MockRepoValidatorMockRecorder {
	return m.recorder
}

// ValidateRepo mocks base method.
func (m *MockRepoValidator) ValidateRepo(ctx context.Context, owner, repo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRepo", ctx, owner, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRepo indicates an expected call of ValidateRepo.
func (mr *MockRepoValidatorMockRecorder) ValidateRepo(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRepo", reflect.TypeOf((*MockRepoValidator)(nil).ValidateRepo), ctx, owner, repo)
}

// MockReleaseFetcher is a mock of ReleaseFetcher interface.
type MockReleaseFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseFetcherMockRecorder
	isgomock struct{}
}

// MockReleaseFetcherMockRecorder is the mock recorder for MockReleaseFetcher.
type MockReleaseFetcherMockRecorder struct {
	mock *MockReleaseFetcher
}

// NewMockReleaseFetcher creates a new mock instance.
func NewMockReleaseFetcher(ctrl *gomock.Controller) *MockReleaseFetcher {
	mock := &MockReleaseFetcher{ctrl: ctrl}
	mock.recorder = &MockReleaseFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseFetcher) EXPECT() *MockReleaseFetcherMockRecorder {
	return m.recorder
}

// GetLatestRelease mocks base method.
func (m *MockReleaseFetcher) GetLatestRelease(ctx context.Context, owner, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, owner, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRelease indicates an expected call of GetLatestRelease.
func (mr *MockReleaseFetcherMockRecorder) GetLatestRelease(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*MockReleaseFetcher)(nil).GetLatestRelease), ctx, owner, repo)
}

// MockReleaseNotifier is a mock of ReleaseNotifier interface.
type MockReleaseNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseNotifierMockRecorder
	isgomock struct{}
}

// MockReleaseNotifierMockRecorder is the mock recorder for MockReleaseNotifier.
type MockReleaseNotifierMockRecorder struct {
	mock *MockReleaseNotifier
}

// NewMockReleaseNotifier creates a new mock instance.
func NewMockReleaseNotifier(ctrl *gomock.Controller) *MockReleaseNotifier {
	mock := &MockReleaseNotifier{ctrl: ctrl}
	mock.recorder = &MockReleaseNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseNotifier) EXPECT() *MockReleaseNotifierMockRecorder {
	return m.recorder
}

// SendReleaseNotification mocks base method.
func (m *MockReleaseNotifier) SendReleaseNotification(ctx context.Context, email, repo, tag, unsubscribeToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReleaseNotification", ctx, email, repo, tag, unsubscribeToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReleaseNotification indicates an expected call of SendReleaseNotification.
func (mr *MockReleaseNotifierMockRecorder) SendReleaseNotification(ctx, email, repo, tag, unsubscribeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReleaseNotification", reflect.TypeOf((*MockReleaseNotifier)(nil).SendReleaseNotification), ctx, email, repo, tag, unsubscribeToken)
}
