// Code generated by MockGen. DO NOT EDIT.
// Source: ../notifierclient/client.go
//
// Generated by this command:
//
//	mockgen -source=../notifierclient/client.go -destination=../notifierclient/mocks/notifierclient_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notifierclient "github.com/Andriy-Sydorenko/repo-release-notifier/internal/notifierclient"
	gomock "go.uber.org/mock/gomock"
)

// MockConfirmationSender is a mock of ConfirmationSender interface.
type MockConfirmationSender struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationSenderMockRecorder
	isgomock struct{}
}

// MockConfirmationSenderMockRecorder is the mock recorder for MockConfirmationSender.
type MockConfirmationSenderMockRecorder struct {
	mock *MockConfirmationSender
}

// NewMockConfirmationSender creates a new mock instance.
func NewMockConfirmationSender(ctrl *gomock.Controller) *MockConfirmationSender {
	mock := &MockConfirmationSender{ctrl: ctrl}
	mock.recorder = &MockConfirmationSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationSender) EXPECT() *MockConfirmationSenderMockRecorder {
	return m.recorder
}

// SendConfirmation mocks base method.
func (m *MockConfirmationSender) SendConfirmation(ctx context.Context, email, repo, confirmToken, unsubscribeToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmation", ctx, email, repo, confirmToken, unsubscribeToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmation indicates an expected call of SendConfirmation.
func (mr *MockConfirmationSenderMockRecorder) SendConfirmation(ctx, email, repo, confirmToken, unsubscribeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmation", reflect.TypeOf((*MockConfirmationSender)(nil).SendConfirmation), ctx, email, repo, confirmToken, unsubscribeToken)
}

// MockReleaseSender is a mock of ReleaseSender interface.
type MockReleaseSender struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseSenderMockRecorder
	isgomock struct{}
}

// MockReleaseSenderMockRecorder is the mock recorder for MockReleaseSender.
type MockReleaseSenderMockRecorder struct {
	mock *MockReleaseSender
}

// NewMockReleaseSender creates a new mock instance.
func NewMockReleaseSender(ctrl *gomock.Controller) *MockReleaseSender {
	mock := &MockReleaseSender{ctrl: ctrl}
	mock.recorder = &MockReleaseSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseSender) EXPECT() *MockReleaseSenderMockRecorder {
	return m.recorder
}

// SendReleaseNotifications mocks base method.
func (m *MockReleaseSender) SendReleaseNotifications(ctx context.Context, repo, tag, notesURL string, recipients []notifierclient.Recipient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReleaseNotifications", ctx, repo, tag, notesURL, recipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReleaseNotifications indicates an expected call of SendReleaseNotifications.
func (mr *MockReleaseSenderMockRecorder) SendReleaseNotifications(ctx, repo, tag, notesURL, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReleaseNotifications", reflect.TypeOf((*MockReleaseSender)(nil).SendReleaseNotifications), ctx, repo, tag, notesURL, recipients)
}

// MockNotifierClient is a mock of NotifierClient interface.
type MockNotifierClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierClientMockRecorder
	isgomock struct{}
}

// MockNotifierClientMockRecorder is the mock recorder for MockNotifierClient.
type MockNotifierClientMockRecorder struct {
	mock *MockNotifierClient
}

// NewMockNotifierClient creates a new mock instance.
func NewMockNotifierClient(ctrl *gomock.Controller) *MockNotifierClient {
	mock := &MockNotifierClient{ctrl: ctrl}
	mock.recorder = &MockNotifierClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifierClient) EXPECT() *MockNotifierClientMockRecorder {
	return m.recorder
}

// SendConfirmation mocks base method.
func (m *MockNotifierClient) SendConfirmation(ctx context.Context, email, repo, confirmToken, unsubscribeToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmation", ctx, email, repo, confirmToken, unsubscribeToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmation indicates an expected call of SendConfirmation.
func (mr *MockNotifierClientMockRecorder) SendConfirmation(ctx, email, repo, confirmToken, unsubscribeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmation", reflect.TypeOf((*MockNotifierClient)(nil).SendConfirmation), ctx, email, repo, confirmToken, unsubscribeToken)
}

// SendReleaseNotifications mocks base method.
func (m *MockNotifierClient) SendReleaseNotifications(ctx context.Context, repo, tag, notesURL string, recipients []notifierclient.Recipient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReleaseNotifications", ctx, repo, tag, notesURL, recipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReleaseNotifications indicates an expected call of SendReleaseNotifications.
func (mr *MockNotifierClientMockRecorder) SendReleaseNotifications(ctx, repo, tag, notesURL, recipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReleaseNotifications", reflect.TypeOf((*MockNotifierClient)(nil).SendReleaseNotifications), ctx, repo, tag, notesURL, recipients)
}
